name: Deploy MultiDocker
on:
  push:
    branches:
      - main 
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # build and run test

      - run: docker build -t matanmagen/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true matanmagen/react-test npm test

      # build and push ------------------>

      - run: docker build -t matanmagen/multi-client-10-14 ./client
      - run: docker build -t matanmagen/multi-nginx-10-14 ./nginx
      - run: docker build -t matanmagen/multi-server-10-14 ./server
      - run: docker build -t matanmagen/multi-worker-10-14 ./worker
 
      - run: docker push matanmagen/multi-client-10-14
      - run: docker push matanmagen/multi-nginx-10-14
      - run: docker push matanmagen/multi-server-10-14
      - run: docker push matanmagen/multi-worker-10-14
 
      # create zip and deploy to EB
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: MultiDocker-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-265892364483
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip